<?php

/**
 *
 * @copyright  2010 frasq.org
 * @version    1
 * @link       http://www.frasq.org
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $head; ?>
</head>
<body>
<?php echo $banner; ?>
<div id="content">
<?php echo $content; ?>
</div>
<?php if (isset($footer)): ?>
<?php echo $footer; ?>
<?php endif; ?>
</body>
</html>
