<?php

/**
 *
 * @copyright  2010-2017 frasq.org
 * @version    3
 * @link       http://www.frasq.org
 */
?>
<div id="bannermenu">
<ul class="menu menubar">
<?php if (isset($contact) and $contact): ?>
<li><a id="mail" href="<?php echo $contact_page; ?>" title="Contact us"><span>Contact</span></a></li>
<?php endif; ?>
<?php if (isset($logout) and $logout): ?>
<li><a id="exit" href="<?php echo $nobody_page; ?>" title="Disconnect"><span>Disconnect</span></a></li>
<?php endif; ?>
<?php if (isset($login) and $login): ?>
<li><a id="enter" href="<?php echo $user_page; ?>" title="Your account"><span>Account</span></a></li>
<?php endif; ?>
<?php if (isset($validate) and $validate): ?>
<li><a id="validate" href="http://validator.w3.org/check?uri=<?php echo $base_root . $validate_page; ?>" target="validator.w3.org" title="Validate"><span>Valider</span></a></li>
<?php endif; ?>
</ul>
</div>
