<?php

/**
 *
 * @copyright  2010-2013 frasq.org
 * @version    2
 * @link       http://www.frasq.org
 *
 * Edité par CORLER Damien
 */

global $aliases;

$aliases = array(
	array(
		'avatar' 				=> 'avatar',
		'captcha' 				=> 'captcha',
	),
	'fr' => array(
		'accueil'				=> 'home',
		'contact'				=> 'contact',
		'utilisateur'			=> 'user',
		'deconnexion'			=> 'nobody',
		'mot-de-passe'			=> 'password',
		'nouvel-utilisateur'	=> 'newuser',
		'noeud'					=> 'node',
        'qrcode'		        => 'qrcode',
        'test'		            => 'test'
	),
	'en' => array(
		'home'					=> 'home',
		'contact'				=> 'contact',
		'user'					=> 'user',
		'disconnect'			=> 'nobody',
		'password'				=> 'password',
		'new-user'				=> 'newuser',
		'node'					=> 'node',
        'qrcode'		        => 'qrcode',
        'test'		            => 'test'
	),
);
