<?php

/**
 *
 * @copyright  2010 frasq.org
 * @version    1
 * @link       http://www.frasq.org
 */

global $strings;

$strings = array(
    array('title' => 'frasq.org',
    ),
    'fr' => array(
        'description' => 'frasq.org : Apprenez comment écrire votre propre CMS en PHP.',
        'keywords' => 'PHP HTML CSS CMS MVC site web language programmation tutoriel manuel cours exemple',
        'http_bad_request:title' => 'Mauvaise requête',
        'http_unauthorized:title' => 'Non autorisé',
        'http_forbidden:title' => 'Interdit',
        'http_not_found:title' => 'Non trouvé',
        'http_internal_error:title' => 'Erreur interne',
        'http_not_implemented:title' => 'Non implémenté',
        'http_service_unavailable:title' => 'Service indisponible',
        'home:title' => 'Accueil',
        'contact:title' => 'Nous contacter',
        'user:title' => 'Identification',
        'newuser:title' => 'Inscription',
        'password:title' => 'Mot de passe',
        'qrcode:title' => 'QR Code',
        'email:salutations' => 'À bientôt.',
        'email:new_password_subject' => 'frasq.org : Votre mot de passe.',
        'email:new_password_text' => "Votre nouveau mot de passe est dans le cryptogramme en pièce jointe.\n\nSi vous n'avez pas demandé à en changer, veuillez ignorer ce message.\nNOTE : Votre ancien mot de passe est toujours valide.\n\nConnectez-vous avec le nouveau mot de passe pour l'activer.",
        'email:new_user_subject' => 'frasq.org : Votre compte.',
        'email:new_user_text' => "Bienvenue !\n\nVotre mot de passe est dans le cryptogramme en pièce jointe.",
    ),
    'en' => array(
        'description' => 'frasq.org : Learn how to write your own CMS in PHP.',
        'keywords' => 'PHP HTML CSS CMS MVC web site langage programming tutorial manual course example',
        'http_bad_request:title' => 'Bad Request',
        'http_unauthorized:title' => 'Unauthorized',
        'http_forbidden:title' => 'Forbidden',
        'http_not_found:title' => 'Not Found',
        'http_internal_error:title' => 'Internal Error',
        'http_not_implemented:title' => 'No Implemented;',
        'http_service_unavailable:title' => 'Service unavailable',
        'home:title' => 'Home',
        'contact:title' => 'Contact us',
        'user:title' => 'Identification',
        'newuser:title' => 'Registration',
        'password:title' => 'Password',
        'qrcode:title' => 'QR Code',
        'email:salutations' => 'See you soon.',
        'email:new_password_subject' => 'frasq.org : Your new password.',
        'email:new_password_text' => "Your new password is in the attached cryptogram.\n\nIf you didn't ask to change it, just ignore this message.\nNOTE: Your old password is still valid.\n\nIdentify yourself with the new password to activate it.",
        'email:new_user_subject' => 'frasq.org : Your account.',
        'email:new_user_text' => "Welcome!\n\nYour password is in the attached cryptogram.",
    ),
);
